Parallel build
opsworks-co/aws-helm-kubectl pull request #18
Opened 2023-09-01 12:38 UTC by atonkyi

2023-09-01 13:51 UTC, sirantd requested changes

2023-09-01 13:51 UTC, sirantd commented on .github/workflows/image-build-push.yaml
> +      - sh-k8s-runner
Why do we have two labels here?
Also, let's have arm in the name, so we know the platform

2023-09-01 13:51 UTC, sirantd commented on .github/workflows/image-build-push.yaml
> +      - name: uname
It's debug, we don't need it anymore

2023-09-01 13:51 UTC, sirantd commented on .github/workflows/image-build-push.yaml
> +      - name: Set up QEMU
Now it can be removed? We don't need emulation anymore.

2023-09-01 13:51 UTC, sirantd commented on dfa
What is that? Why do we need this file?

2023-09-01 15:05 UTC, atonkyi commented on .github/workflows/image-build-push.yaml
> +      - name: Set up QEMU
No, because without this block it is not working, even in a current version https://prnt.sc/UFp4zoznXbMw

2023-09-01 15:08 UTC, atonkyi commented on dfa
Not sure, but it was created automatically - now I deleted it

2023-09-04 11:55 UTC, sirantd approved these changes

2023-09-04 11:57 UTC, merged